export const DISPLACE_STUDENT = 'DISPLACE_STUDENT';
export const UNPLACE_STUDENT = 'UNPLACE_STUDENT';
export const ADD_STUDENT_TO_ROOM = 'ADD_STUDENT_TO_ROOM';
export const ADD_NEW_ROOM = 'ADD_NEW_ROOM';
export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
